"""empty message

Revision ID: 7292f5aabbd3
Revises: 
Create Date: 2021-10-11 02:32:09.082182

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7292f5aabbd3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('materials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('SO2', sa.Float(), nullable=False),
    sa.Column('NO2', sa.Float(), nullable=False),
    sa.Column('CO', sa.Float(), nullable=False),
    sa.Column('O3', sa.Integer(), nullable=False),
    sa.Column('PM10', sa.Integer(), nullable=False),
    sa.Column('PM2_5', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('materials')
    # ### end Alembic commands ###
